//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VillaMouzinho.Business.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class app_countries
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string COD_ALPHA2 { get; set; }
        public string COD_ALPHA3 { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
    }
}
