//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VillaMouzinho.Business.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class aspnetuser_recover_password_token
    {
        public int ID { get; set; }
        public string EMAIL { get; set; }
        public string TOKEN { get; set; }
        public bool IS_BLOCKED { get; set; }
    }
}
