//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VillaMouzinho.Business.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class attributes_values
    {
        public int ID { get; set; }
        public int ATTRIBUTE_ID { get; set; }
        public string VALUE { get; set; }
        public string DESCRIPTION { get; set; }
    
        public virtual attributes attributes { get; set; }
    }
}
