//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VillaMouzinho.Business.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_page_module_room_attributes
    {
        public int ID { get; set; }
        public int ROOM_ID { get; set; }
        public int ATTRIBUTE_ID { get; set; }
        public int ATTRIBUTE_VALUE_ID { get; set; }
    }
}
