//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VillaMouzinho.Business.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_page_header
    {
        public int IID { get; set; }
        public string ID { get; set; }
        public int STATUS { get; set; }
        public int TYPE { get; set; }
        public string TITLE { get; set; }
        public string URL { get; set; }
        public string PARENT_ID { get; set; }
        public string PARENT_PATH { get; set; }
        public bool ACTIVE { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
    }
}
