//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VillaMouzinho.Business.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_page_module_room
    {
        public int ID { get; set; }
        public string TITLE { get; set; }
        public string DESCRIPTION { get; set; }
        public byte[] IMAGE { get; set; }
        public string EXTENSION { get; set; }
        public string IMAGE_NAME { get; set; }
        public Nullable<decimal> HIGHER_PRICE { get; set; }
        public Nullable<decimal> LOWER_PRICE { get; set; }
    }
}
