//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VillaMouzinho.Business.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_page_module_mapping
    {
        public int ID { get; set; }
        public string PAGE_HEADER_ID { get; set; }
        public int PAGE_HEADER_IID { get; set; }
        public string TYPE { get; set; }
        public int MODULE_ID { get; set; }
        public int ORDER { get; set; }
    }
}
