//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VillaMouzinho.Business.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbEntities : DbContext
    {
        public dbEntities()
            : base("name=dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C__migrationhistory> C__migrationhistory { get; set; }
        public DbSet<aspnetroles> aspnetroles { get; set; }
        public DbSet<aspnetuser_recover_password_token> aspnetuser_recover_password_token { get; set; }
        public DbSet<aspnetuserclaims> aspnetuserclaims { get; set; }
        public DbSet<aspnetuserroles> aspnetuserroles { get; set; }
        public DbSet<aspnetusers> aspnetusers { get; set; }
        public DbSet<attributes> attributes { get; set; }
        public DbSet<attributes_values> attributes_values { get; set; }
        public DbSet<cms_page_header> cms_page_header { get; set; }
        public DbSet<cms_page_module_content> cms_page_module_content { get; set; }
        public DbSet<cms_page_module_mapping> cms_page_module_mapping { get; set; }
        public DbSet<aspnetuserlogins> aspnetuserlogins { get; set; }
    }
}
